---
- name: "Download Wordpress"
  get_url:
    url: 'http://wordpress.org/latest.tar.gz'
    dest: '/tmp/latest.tar.gz'

- name: "descompacta o wordpress"
  unarchive:
    src: /tmp/latest.tar.gz
    dest: /var/www
    remote_src: yes
  become: yes

- name: "copia o arquivo config para o wordpress"
  copy:
    src: "{{ wp_dir_path }}/wp-config-sample.php"
    dest: "{{ wp_dir_path }}/wp-config.php"
    remote_src: yes
  become: yes

- name: "mudando o config"
  replace:
    path: "{{ wp_dir_path }}/wp-config.php"
    regexp: "{{ item.regex }}"
    replace: "{{ item.value }}"
  with_items:
    - { regex: 'database_name_here', value: "{{ wp_db_name }}"}
    - { regex: 'username_here', value: "{{ wp_db_username }}"}
    - { regex: 'password_here', value: "{{ wp_db_user_pass }}"}
    - { regex: 'localhost', value: "{{ wp_db_ip }}"}
  become: yes