---
- name: 'instalando pacotes do bd'
  apt:
    name: "{{ item }}"
    state: latest
  become: yes
  with_items:
  - mysql-server
  - python-mysqldb
  - python3-mysqldb

- name: "criando o banco"
  mysql_db:
    name: "{{ wp_db_name }}"
    login_user: root
    state: present
  become: yes

- name: "criando o usuario do banco"
  mysql_user:
    name: "{{ wp_db_username }}"
    login_user: root
    password: "{{ wp_db_user_pass }}"
    priv: "{{ wp_db_name }}.*:ALL,GRANT"
    state: present
    host: "{{ item }}"
  become: yes
  with_items:
    - "{{ wp_web_ip }}"

- name: 'configura o mysql para conexoes remotas'
  copy:
    src: 'files/mysqld.cnf'
    dest: '/etc/mysql/mysql.conf.d/mysqld.cnf'
  become: yes
  notify:
    - restart mysql